name: fiap-github-actions
# run-name: ${{ github.actor }} is learning GitHub Actions
run-name: Meetup Fiap
on: [push, workflow_dispatch]
jobs:

  # analise de composição de software
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

  # analise dinamica / precisa estar publicada
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://159.223.170.3/'
