name: fiap-github-actions
# run-name: ${{ github.actor }} is learning GitHub Actions
run-name: Meetup Fiap
on: [push, workflow_dispatch]
jobs:

  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
